# PrivacyIDEA Configuration
privacyidea:
  image:
    repository: gpappsoft/privacyidea-docker
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  env:
    PI_ADMIN: admin
    PI_ADMIN_PASS: admin
    #PI_ADDRESS: 0.0.0.0 
    #PI_PORT: 8080
    PI_LOGLEVEL: INFO
    PI_PEPPER: changeMe
    PI_SECRET: changeMe
    #PI_ENCKEY: 9KraeeWGbIANYFHS+4L4YY2uRE/xP3pdeMZ5hrHYagmFo5vbYxNcruv4mh2P/pX6xUp+Px/AKLPANzi1s3N4O2vWEC7a2yzk3o4LcWKupFAbW/Jl1kM16EvCyCQ9hpKe
    SUPERUSER_REALM: "admin,helpdesk"
    SQLALCHEMY_ENGINE_OPTIONS: False
    #PI_AUDIT_NO_SIGN: False
    #PI_AUDIT_SQL_URI:
    #REDIS_URL: 
    #DB_HOST: 
    #DB_PORT: 3306
    #DB_NAME: 
    #DB_USER: 
    #DB_PASSWORD: 
    DB_API: mysql+pymysql
    DB_EXTRA_PARAMS: "?charset=utf8"
  persistence:
    enabled: true
    size: 1Gi

  resources: {}
  #  limits:
  #    cpu: "1"
  #    memory: "512Mi"
  #  requests:
  #    cpu: "0.5"
  #    memory: "256Mi"

# MariaDB Configuration
mariadb:
  enabled: true
  image:
    repository: mariadb
    tag: "10.6"
    pullPolicy: IfNotPresent
  auth:
    rootPassword: "rootpassword"
    username: privacyidea
    password: "privacyidea"
    database: privacyidea
  persistence:
    enabled: true
    size: 10Gi

# Redis Configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: "6"
    pullPolicy: IfNotPresent
  password: "privacyidea"
  persistence:
    enabled: true
    size: 5Gi
