# PrivacyIDEA Configuration
privacyidea:
  image:
    repository: gpappsoft/privacyidea-docker
    tag: "3.11"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  env:
    piAdmin: admin
    piAdminPass: admin
    #piAddress: 0.0.0.0 
    piLoglevel: INFO
    piPepper: changeMe
    piSecret: changeMe
    #piEncKey: 9KraeeWGbIANYFHS+4L4YY2uRE/xP3pdeMZ5hrHYagmFo5vbYxNcruv4mh2P/pX6xUp+Px/AKLPANzi1s3N4O2vWEC7a2yzk3o4LcWKupFAbW/Jl1kM16EvCyCQ9hpKe
    superuserRealm: "admin,helpdesk"
    sqlalchemyEngineOptions: False
    piAuditNoSign: False
    #piAuditSqlUri:
    #redisUrl: 
    #dbHost: 
    #dbPort: "3306"
    #dbName:
    #dbUser: 
    #dbPassword: 
    dbApi: mysql+pymysql
    dbExtraParams: "?charset=utf8"
  persistence:
    enabled: true
    size: 1Gi
  resources: {}
  #  limits:
  #    cpu: "1"
  #    memory: "512Mi"
  #  requests:
  #    cpu: "0.5"
  #    memory: "256Mi"

# MariaDB Configuration
mariadb:
  enabled: true
  image:
    repository: mariadb
    tag: "10.6"
    pullPolicy: IfNotPresent
  auth:
    rootPassword: "rootpassword"
    username: privacyidea
    password: "privacyidea"
    database: privacyidea
  persistence:
    enabled: true
    size: 10Gi

# Enable or disable radius
radius:
  enabled: false
  image:
    repository: gpappsoft/privacyidea-freeradius
    tag: "3.4.3-1"
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 1812
  env:
    #piHost:
    #piPort: 
    piRealm:
    piResconf:
    piSslcheck: False
    piTimeout: 10

# Redis Configuration
redis:
  enabled: true
  image:
    repository: redis
    tag: "6"
    pullPolicy: IfNotPresent
  password: "privacyidea"
  persistence:
    enabled: true
    size: 5Gi

# Enable or disable ingress
ingress:
  enabled: false