apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
    piPort: "{{ .Values.piPort | default "8080" }}"
    piAdminName: "{{ .Values.piAdminName | default "admin" }}"
    piBootstrap: "{{ .Values.piBootstrap | default "true" }}"
    piUpdate: "{{ .Values.piUpdate | default "false" }}"
    piLogLevel: "{{ .Values.piLogLevel | default "INFO"| upper }}"
    superuserRealm: "{{ .Values.piBootstrap | default "admin,helpdesk" }}"
    dbApi: "{{ .Values.dbApi }}"
    dbUser: "{{ .Values.dbUser }}"
    dbHost: "{{ .Values.dbHost }} "
    dbPort: "{{ .Values.dbPort }}"
    dbName: "{{ .Values.dbName | default "pi" }}"
    dbPassword: "{{ .Values.dbPassword | default "null" }}"
    dbExtraParams: "{{ .Values.dbExtraParams }}"
    piSecretsPath: "{{ .Values.piSecretPath | default "/etc/privacyidea/secrets"}}"