apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-privacyidea
  labels:
    app: privacyidea
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.privacyidea.replicaCount }}
  selector:
    matchLabels:
      app: privacyidea
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: privacyidea
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: privacyidea
        image: "{{ .Values.privacyidea.image.repository }}:{{ .Values.privacyidea.image.tag }}"
        imagePullPolicy: {{ .Values.privacyidea.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.privacyidea.service.port }}
        env:
        - name: PI_ADMIN
          value: {{ .Values.privacyidea.env.PI_ADMIN }}
        - name: PI_ADMIN_PASS
          value: {{ .Values.privacyidea.env.PI_ADMIN_PASS }}
        - name: PI_ADDRESS
          value: "0.0.0.0"
        - name: PI_PORT
          value: "{{ .Values.privacyidea.service.port }}"
        - name: PI_LOGLEVEL
          value: {{ .Values.privacyidea.env.PI_LOGLEVEL }}
        - name: PI_PEPPER
          value: {{ .Values.privacyidea.env.PI_PEPPER }}
        - name: PI_SECRET
          value: {{ .Values.privacyidea.env.PI_SECRET }}
        - name: SUPERUSER_REALM
          value: {{ .Values.privacyidea.env.SUPERUSER_REALM }}
        - name: SQLALCHEMY_ENGINE_OPTIONS
          value: "{{ .Values.privacyidea.env.SQLALCHEMY_ENGINE_OPTIONS }}"
        - name: REDIS_URL
          value: "redis://:{{ .Values.redis.password }}@{{ .Release.Name }}-redis-master:6379/0"
        #- name: PI_ENCKEY
        #  value: {{ .Values.privacyidea.env.PI_ENCKEY }}
        - name: DB_HOST
          value: {{ .Release.Name }}-mariadb
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: {{ .Values.mariadb.auth.database }}
        - name: DB_USER
          value: {{ .Values.mariadb.auth.username }}
        - name: DB_PASSWORD
          value: {{ .Values.mariadb.auth.password }}
        - name: DB_API
          value: {{ .Values.privacyidea.env.DB_API }}
        - name: DB_EXTRA_PARAMS
          value: {{ .Values.privacyidea.env.DB_EXTRA_PARAMS }}
        resources:
{{ toYaml .Values.privacyidea.resources | indent 10 }}
        volumeMounts:
        - name: privacyidea-data
          mountPath: /privacyidea/etc/persistent/
      volumes:
      - name: privacyidea-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-piconfig-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-piconfig-pvc
  labels:
    app: privacyidea
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.privacyidea.persistence.size }}


